# Generated by Django 4.2.7 on 2023-11-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='message',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
