# Generated by Django 4.2.7 on 2023-11-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solved',
            name='instructions',
        ),
    ]
