# Generated by Django 4.2.7 on 2023-11-30 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_order_created_order_updated_rating_created_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='api.order'),
        ),
    ]
