# Generated by Django 4.2.7 on 2023-11-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_chat_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='model',
            new_name='order',
        ),
    ]
